// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGLIFoAipNwYmuEkCRUTxBaip6YlMJu4o',
    appId: '1:865637462814:web:b7753fe9a3ed32c9e10f0f',
    messagingSenderId: '865637462814',
    projectId: 'loginfirebase-f957e',
    authDomain: 'loginfirebase-f957e.firebaseapp.com',
    storageBucket: 'loginfirebase-f957e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY_NfTJfe5FnCfTpbbczeU21HHTHbdwfY',
    appId: '1:865637462814:android:93f91202d73cb562e10f0f',
    messagingSenderId: '865637462814',
    projectId: 'loginfirebase-f957e',
    storageBucket: 'loginfirebase-f957e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDRp7ayZYv8_a9pNSR5rpJdbncVCr6f5Y',
    appId: '1:865637462814:ios:dd053807c58da44ce10f0f',
    messagingSenderId: '865637462814',
    projectId: 'loginfirebase-f957e',
    storageBucket: 'loginfirebase-f957e.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDRp7ayZYv8_a9pNSR5rpJdbncVCr6f5Y',
    appId: '1:865637462814:ios:dd053807c58da44ce10f0f',
    messagingSenderId: '865637462814',
    projectId: 'loginfirebase-f957e',
    storageBucket: 'loginfirebase-f957e.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGLIFoAipNwYmuEkCRUTxBaip6YlMJu4o',
    appId: '1:865637462814:web:8e186f2d20f00aaee10f0f',
    messagingSenderId: '865637462814',
    projectId: 'loginfirebase-f957e',
    authDomain: 'loginfirebase-f957e.firebaseapp.com',
    storageBucket: 'loginfirebase-f957e.appspot.com',
  );
}
